/**
 * One-click setup for OpenCode plugin.
 * Installs/removes a JS plugin at ~/.config/opencode/plugins/event-horizon.mjs
 * that forwards OpenCode events to Event Horizon's HTTP server.
 */

import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

const PORT = 28765;
const PLUGIN_FILENAME = 'event-horizon.mjs';

/** Marker comment at the top of the plugin file so we can identify it. */
const MARKER = '// @event-horizon/opencode-plugin';

function getPluginDir(): string {
  return path.join(os.homedir(), '.config', 'opencode', 'plugins');
}

function getPluginPath(): string {
  return path.join(getPluginDir(), PLUGIN_FILENAME);
}

function buildPluginSource(): string {
  return `${MARKER}
// Auto-generated by Event Horizon VS Code extension.
// Forwards OpenCode events to the Event Horizon visualization server.

const PORT = ${PORT};
const URL = \`http://127.0.0.1:\${PORT}/opencode\`;

async function send(eventName, data) {
  try {
    await fetch(URL, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ event: eventName, ...data }),
    });
  } catch {
    // Event Horizon server not running — silently ignore
  }
}

export const EventHorizon = async (ctx) => {
  const sessionId = ctx.project?.id ?? "opencode-1";
  const agentName = "OpenCode";

  return {
    "session.created": async (input) => {
      await send("session.created", { sessionId, agentName, payload: input });
    },
    "session.deleted": async (input) => {
      await send("session.deleted", { sessionId, agentName, payload: input });
    },
    "session.idle": async (input) => {
      await send("session.idle", { sessionId, agentName, payload: input });
    },
    "session.error": async (input) => {
      await send("session.error", { sessionId, agentName, payload: input });
    },
    "tool.execute.before": async (input) => {
      const toolName = input?.tool ?? input?.name ?? undefined;
      await send("tool.execute.before", { sessionId, agentName, payload: { ...input, toolName } });
    },
    "tool.execute.after": async (input) => {
      const toolName = input?.tool ?? input?.name ?? undefined;
      await send("tool.execute.after", { sessionId, agentName, payload: { ...input, toolName } });
    },
    "message.updated": async (input) => {
      await send("message.updated", { sessionId, agentName, payload: input });
    },
    "file.edited": async (input) => {
      await send("file.edited", { sessionId, agentName, payload: input });
    },
  };
};
`;
}

/** Returns true if the Event Horizon plugin file exists. */
export function isOpenCodeHooksInstalled(): boolean {
  try {
    const content = fs.readFileSync(getPluginPath(), 'utf8');
    return content.includes(MARKER);
  } catch {
    return false;
  }
}

/** Removes the Event Horizon plugin file. */
export function removeOpenCodeHooks(): void {
  const pluginPath = getPluginPath();
  try {
    if (fs.existsSync(pluginPath)) {
      const content = fs.readFileSync(pluginPath, 'utf8');
      if (content.includes(MARKER)) {
        fs.unlinkSync(pluginPath);
      }
    }
  } catch {
    // Nothing to remove
  }
}

/** Writes the Event Horizon plugin file. */
export function setupOpenCodeHooks(): void {
  const dir = getPluginDir();
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(getPluginPath(), buildPluginSource(), 'utf8');
}

export async function runSetupOpenCodeHooks(): Promise<void> {
  try {
    setupOpenCodeHooks();
    void vscode.window.showInformationMessage(
      'Event Horizon: OpenCode plugin installed! Restart OpenCode to see your agent appear.',
    );
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    void vscode.window.showErrorMessage(`Event Horizon: Failed to install OpenCode plugin — ${msg}`);
  }
}
