/**
 * One-click setup for OpenCode plugin.
 * Installs/removes a JS plugin at ~/.config/opencode/plugins/event-horizon.ts
 * that forwards OpenCode events to Event Horizon's HTTP server.
 *
 * OpenCode auto-loads .ts files from ~/.config/opencode/plugins/ at startup.
 * Users must restart OpenCode after installing the plugin.
 */

import * as vscode from 'vscode';
import * as fsp from 'fs/promises';
import * as path from 'path';
import * as os from 'os';
import { getAuthToken } from './eventServer.js';

const PORT = 28765;
const PLUGIN_FILENAME = 'event-horizon.ts';

/** Marker comment so we can identify our plugin file. */
const MARKER = '// @event-horizon/opencode-plugin';

function getPluginDir(): string {
  return path.join(os.homedir(), '.config', 'opencode', 'plugins');
}

function getPluginPath(): string {
  return path.join(getPluginDir(), PLUGIN_FILENAME);
}

function buildPluginSource(): string {
  const token = getAuthToken() ?? '';
  const tokenParam = token ? `?token=${token}` : '';
  return `${MARKER}
// Auto-generated by Event Horizon VS Code extension.
// Forwards OpenCode events to the Event Horizon visualization server.
// Do not edit — reinstall from Event Horizon's Connect panel.

const PORT = ${PORT};
const TOKEN_PARAM = "${tokenParam}";

function send(eventName, extra) {
  const body = JSON.stringify({ event: eventName, ...extra });
  fetch("http://127.0.0.1:" + PORT + "/opencode" + TOKEN_PARAM, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body,
  }).catch(() => {});
}

function sendExit(eventName, extra) {
  send(eventName, extra);
  try {
    const { spawnSync } = require("node:child_process");
    const body = JSON.stringify({ event: eventName, ...extra });
    spawnSync("node", ["-e",
      "require('http').request({hostname:'127.0.0.1',port:" + PORT +
      ",path:'/opencode" + TOKEN_PARAM + "',method:'POST',headers:{'Content-Type':'application/json'}}" +
      ",()=>process.exit()).end(" + JSON.stringify(body) + ")"
    ], { timeout: 2000, stdio: "ignore" });
  } catch {}
}

export default async function EventHorizon({ project }) {
  const sessionId = String(project?.id ?? "opencode-1");
  const agentName = "OpenCode";

  send("session.created", { sessionId, agentName, payload: {} });

  // Send session.deleted when OpenCode exits (Ctrl+C, exit command, etc.)
  const onExit = () => sendExit("session.deleted", { sessionId, agentName, payload: {} });
  process.on("beforeExit", onExit);
  process.on("SIGINT", () => { onExit(); process.exit(0); });
  process.on("SIGTERM", () => { onExit(); process.exit(0); });

  return {
    event: async ({ event }) => {
      send(event?.type ?? "unknown", {
        sessionId,
        agentName,
        payload: event ?? {},
      });
    },
    "tool.execute.before": async (input) => {
      send("tool.execute.before", {
        sessionId,
        agentName,
        payload: { toolName: input?.tool, sessionID: input?.sessionID, callID: input?.callID },
      });
    },
    "tool.execute.after": async (input) => {
      send("tool.execute.after", {
        sessionId,
        agentName,
        payload: { toolName: input?.tool, sessionID: input?.sessionID, callID: input?.callID },
      });
    },
  };
};
`;
}

/** Returns true if the Event Horizon plugin file exists. */
export async function isOpenCodeHooksInstalled(): Promise<boolean> {
  try {
    const content = await fsp.readFile(getPluginPath(), 'utf8');
    return content.includes(MARKER);
  } catch {
    return false;
  }
}

/** Removes the Event Horizon plugin file. */
export async function removeOpenCodeHooks(): Promise<void> {
  const pluginPath = getPluginPath();
  try {
    const content = await fsp.readFile(pluginPath, 'utf8');
    if (content.includes(MARKER)) {
      await fsp.unlink(pluginPath);
    }
  } catch {
    // Nothing to remove
  }
}

/** Writes the Event Horizon plugin file. */
export async function setupOpenCodeHooks(): Promise<void> {
  const dir = getPluginDir();
  await fsp.mkdir(dir, { recursive: true });
  // Remove old .mjs version if present
  const oldMjs = path.join(dir, 'event-horizon.mjs');
  try { await fsp.unlink(oldMjs); } catch { /* ignore */ }
  await fsp.writeFile(getPluginPath(), buildPluginSource(), 'utf8');
}

export async function runSetupOpenCodeHooks(): Promise<void> {
  try {
    await setupOpenCodeHooks();
    void vscode.window.showInformationMessage(
      'Event Horizon: OpenCode plugin installed! Restart OpenCode to see your agent appear.',
    );
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    void vscode.window.showErrorMessage(`Event Horizon: Failed to install OpenCode plugin — ${msg}`);
  }
}
