/**
 * One-click setup for OpenCode plugin.
 * Installs/removes a JS plugin at ~/.config/opencode/plugins/event-horizon.ts
 * that forwards OpenCode events to Event Horizon's HTTP server.
 *
 * OpenCode auto-loads .ts files from ~/.config/opencode/plugins/ at startup.
 * Users must restart OpenCode after installing the plugin.
 */

import * as vscode from 'vscode';
import * as fsp from 'fs/promises';
import * as path from 'path';
import * as os from 'os';
import { getAuthToken } from './eventServer.js';

const PORT = 28765;
const PLUGIN_FILENAME = 'event-horizon.ts';

/** Marker comment so we can identify our plugin file. */
const MARKER = '// @event-horizon/opencode-plugin';

function getPluginDir(): string {
  return path.join(os.homedir(), '.config', 'opencode', 'plugins');
}

function getPluginPath(): string {
  return path.join(getPluginDir(), PLUGIN_FILENAME);
}

function buildPluginSource(): string {
  const token = getAuthToken() ?? '';
  const tokenParam = token ? `?token=${token}` : '';
  return `${MARKER}
// Auto-generated by Event Horizon VS Code extension.
// Forwards OpenCode events to the Event Horizon visualization server.
// Do not edit — reinstall from Event Horizon's Connect panel.

const PORT = ${PORT};
const TOKEN_PARAM = "${tokenParam}";

function send(eventName, extra) {
  const body = JSON.stringify({ event: eventName, ...extra });
  fetch("http://127.0.0.1:" + PORT + "/opencode" + TOKEN_PARAM, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body,
  }).catch(() => {});
}

async function checkLock(filePath, agentId, agentName) {
  try {
    const resp = await fetch("http://127.0.0.1:" + PORT + "/lock" + TOKEN_PARAM, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: "check", filePath, agentId, agentName }),
      signal: AbortSignal.timeout(2000),
    });
    if (resp.status === 409) {
      const data = await resp.json();
      throw new Error("[Event Horizon file lock] BLOCKED: " + filePath + " is locked by " + (data.owner || "another agent") + " who is actively editing it. You MUST NOT write to this file by ANY means — no Write, no Edit, no Bash echo/cat/sed, no workarounds. The lock will release automatically when they finish (within 30 seconds of their last write). Work on OTHER files first, then retry this file later.");
    }
  } catch (e) {
    if (e && e.message && e.message.includes("is locked by")) throw e;
    // Ignore network errors — Event Horizon might not be running
  }
}

async function releaseLock(filePath, agentId) {
  try {
    await fetch("http://127.0.0.1:" + PORT + "/lock" + TOKEN_PARAM, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ action: "release", filePath, agentId }),
      signal: AbortSignal.timeout(2000),
    });
  } catch {}
}

function sendExit(eventName, extra) {
  send(eventName, extra);
  try {
    const { spawnSync } = require("node:child_process");
    const body = JSON.stringify({ event: eventName, ...extra });
    spawnSync("node", ["-e",
      "require('http').request({hostname:'127.0.0.1',port:" + PORT +
      ",path:'/opencode" + TOKEN_PARAM + "',method:'POST',headers:{'Content-Type':'application/json'}}" +
      ",()=>process.exit()).end(" + JSON.stringify(body) + ")"
    ], { timeout: 2000, stdio: "ignore" });
  } catch {}
}

export default async function EventHorizon({ project, directory, worktree, serverUrl }) {
  // Use project.id when available, but always append a unique suffix so
  // multiple OpenCode instances in the same project get separate planets.
  const base = project?.id ? String(project.id) : "opencode";
  const uid = Date.now().toString(36) + Math.random().toString(36).slice(2, 6);
  const sessionId = base + "-" + uid;
  const cwd = worktree || directory || undefined;
  const cwdFolder = cwd ? String(cwd).replace(/\\\\/g, "/").split("/").pop() : undefined;
  const agentName = cwdFolder ? "OpenCode (" + cwdFolder + ")" : "OpenCode";
  // OpenCode's internal server URL — used by Event Horizon for SSE subagent tracking
  const opencodeServerUrl = typeof serverUrl === "object" && serverUrl?.href ? serverUrl.href : undefined;

  // Send initial session.created
  send("session.created", { sessionId, agentName, cwd, payload: {}, serverUrl: opencodeServerUrl });

  // Continuously re-send session.created as a heartbeat so Event Horizon
  // can discover this agent even if it started after OpenCode.
  // Runs every 30 seconds indefinitely - Event Horizon deduplicates spawns.
  const heartbeatInterval = setInterval(() => {
    send("session.created", { sessionId, agentName, cwd, payload: { heartbeat: true }, serverUrl: opencodeServerUrl });
  }, 30000);

  // Send session.deleted when OpenCode exits (Ctrl+C, exit command, etc.)
  const onExit = () => {
    clearInterval(heartbeatInterval);
    sendExit("session.deleted", { sessionId, agentName, cwd, payload: {} });
  };
  process.on("beforeExit", onExit);
  process.on("SIGINT", () => { onExit(); process.exit(0); });
  process.on("SIGTERM", () => { onExit(); process.exit(0); });

  return {
    event: async ({ event }) => {
      send(event?.type ?? "unknown", {
        sessionId,
        agentName,
        cwd,
        payload: event ?? {},
      });
    },
    "tool.execute.before": async (input) => {
      send("tool.execute.before", {
        sessionId,
        agentName,
        cwd,
        payload: { toolName: input?.tool, sessionID: input?.sessionID, callID: input?.callID },
      });
      // Check file lock for any tool that accesses files
      const toolName = String(input?.tool || "").toLowerCase();
      const fileTool = ["read", "write", "edit", "patch", "file_read", "file_write", "file_edit"].includes(toolName);
      const fp = input?.input?.file_path || input?.input?.path;
      if (fileTool && fp) {
        await checkLock(String(fp), sessionId, agentName);
      }
    },
    "tool.execute.after": async (input) => {
      send("tool.execute.after", {
        sessionId,
        agentName,
        cwd,
        payload: { toolName: input?.tool, sessionID: input?.sessionID, callID: input?.callID },
      });
      // Locks NOT released here — auto-expire via 30s TTL.
      // Each tool.execute.before refreshes the TTL.
      if (false) { // keep releaseLock available for future use
        const fp = input?.input?.file_path || input?.input?.path;
        if (fp) await releaseLock(String(fp), sessionId);
      }
    },
    "permission.asked": async (input) => {
      send("permission.asked", {
        sessionId,
        agentName,
        cwd,
        payload: { tool: input?.tool, permission: input?.permission },
      });
    },
    "permission.replied": async (input) => {
      send("permission.replied", {
        sessionId,
        agentName,
        cwd,
        payload: { tool: input?.tool, granted: input?.granted },
      });
    },
  };
};
`;
}

/** Returns true if the Event Horizon plugin file exists (any token version). */
export async function isOpenCodeHooksInstalled(): Promise<boolean> {
  try {
    const content = await fsp.readFile(getPluginPath(), 'utf8');
    return content.includes(MARKER);
  } catch {
    return false;
  }
}

/** Returns true if the plugin file exists but with a stale token. */
export async function hasStaleOpenCodeHooks(): Promise<boolean> {
  try {
    const content = await fsp.readFile(getPluginPath(), 'utf8');
    if (!content.includes(MARKER)) return false;
    const token = getAuthToken();
    if (token) return !content.includes(`token=${token}`);
    return false;
  } catch {
    return false;
  }
}

/** Removes the Event Horizon plugin file. */
export async function removeOpenCodeHooks(): Promise<void> {
  const pluginPath = getPluginPath();
  try {
    const content = await fsp.readFile(pluginPath, 'utf8');
    if (content.includes(MARKER)) {
      await fsp.unlink(pluginPath);
    }
  } catch {
    // Nothing to remove
  }
}

/** Writes the Event Horizon plugin file. */
export async function setupOpenCodeHooks(): Promise<void> {
  const dir = getPluginDir();
  await fsp.mkdir(dir, { recursive: true });
  // Remove old .mjs version if present
  const oldMjs = path.join(dir, 'event-horizon.mjs');
  try { await fsp.unlink(oldMjs); } catch { /* ignore */ }
  await fsp.writeFile(getPluginPath(), buildPluginSource(), 'utf8');
}

/**
 * Register Event Horizon as an MCP server in OpenCode's config.
 * Reads ~/.config/opencode/opencode.json, merges our entry under "mcp".
 */
export async function registerOpenCodeMcpServer(): Promise<void> {
  const configPath = path.join(os.homedir(), '.config', 'opencode', 'opencode.json');
  const token = getAuthToken();
  const tokenParam = token ? `?token=${token}` : '';
  const mcpUrl = `http://127.0.0.1:${PORT}/mcp${tokenParam}`;

  let config: Record<string, unknown> = {};
  try {
    const raw = await fsp.readFile(configPath, 'utf8');
    config = JSON.parse(raw);
  } catch {
    // File doesn't exist or is invalid — start fresh
  }

  const mcp = (config.mcp ?? {}) as Record<string, unknown>;
  mcp['event-horizon'] = { type: 'remote', url: mcpUrl, enabled: true };
  config.mcp = mcp;

  const dir = path.dirname(configPath);
  await fsp.mkdir(dir, { recursive: true });
  await fsp.writeFile(configPath, JSON.stringify(config, null, 2), 'utf8');
}

export async function runSetupOpenCodeHooks(): Promise<void> {
  try {
    await setupOpenCodeHooks();
    await registerOpenCodeMcpServer();
    void vscode.window.showInformationMessage(
      'Event Horizon: OpenCode plugin + MCP tools installed! Restart OpenCode to see your agent appear.',
    );
  } catch (e) {
    const msg = e instanceof Error ? e.message : String(e);
    void vscode.window.showErrorMessage(`Event Horizon: Failed to install OpenCode plugin — ${msg}`);
  }
}
